# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger: none

jobs:
- job: node
  pool:
    vmImage: 'windows-latest'
  steps:
  - task: NodeTool@0
    inputs:
      versionSource: 'spec'
      versionSpec: '20.x'
      checkLatest: true
    displayName: 'install node'
  
- job: dependencies
  dependsOn: node
  pool:
    vmImage: 'windows-latest'
  steps:
  - script: rm -rf node_modules && npm i && npm i react-scripts --save
    displayName: 'install dependencies'

# - job: server
#   dependsOn: dependencies
#   pool:
#     vmImage: 'windows-latest'
#   steps:
#   - script: cd ".\src\server\" && node server.js
#     displayName: 'start server'

# - job: app
#   dependsOn: dependencies
#   pool:
#     vmImage: 'windows-latest'
#   steps:
#   - script: npm start
#     displayName: 'start app'

# - job: test
#   dependsOn: app
#   pool:
#     vmImage: 'windows-latest'
#   steps:
#   - script: npm test
#     displayName: 'test app'