# Node.js with React
# Build a Node.js project that uses React.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

trigger:
- main

pool:
  vmImage: windows-latest

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'
  displayName: 'Install Node.js'

- script: |
    gnome-terminal --command
    echo hi
    gnome-terminal --command
    echo hello
    # npm install
    # node app.js
    # sleep 5
    # gnome-terminal --command
    # node .\src\server\server.js
    # npm run test
  # displayName: 'npm install, build and test'
